import React from "react";

function Head() {
    return (
        <>
        <title>Next Js 13 | Blog</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
        </>
    );
}

export default Head;